version: "3.9"
networks:
  lan:
services:
  postgres14:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    expose:
      - 5432
    container_name: pg_bp
    environment:
      POSTGRES_USER: 'koa_bp'
      POSTGRES_PASSWORD: '12345678'
    volumes:
      - ~/databases/koa_bp/postgres14:/data
